version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    working_directory: /go/src/github.com/bitnami/ini-file
    steps:
      - checkout
      - run: make get-build-deps
      - run: make download
      - run: make vet
      - run: make lint
      - run: make cover
      - run: make build TOOL_PATH=out/ini-file
      - run: make build/arm64 TOOL_PATH=out/arm64/ini-file
      - store_artifacts:
          path: /go/src/github.com/bitnami/ini-file/out/ini-file
          destination: ini-file
      - store_artifacts:
          path: /go/src/github.com/bitnami/ini-file/out/arm64/ini-file
          destination: ini-file-arm64
